//! This is an internal `registry` of all available `notes`
//! 
//! `registry` is an entry point for all contained `notes` and it mods them all, so I can run all existing `doc tests`
//! also `registry` contains an `array` of all `notes` full paths, which is used in `Registry` API implementation inside `lib.rs`
//! 
//! The contents of this file are generated by the `build.rs` script. Do not edit manually

pub(crate) mod strings;
pub(crate) mod borrow_checker;
pub(crate) mod ownership_system;
pub(crate) mod sized_trait;
pub(crate) mod lifetimes;


/// Special array containing all `note`s full paths
pub(crate) const TABLETS: [&str; 5] = [
	concat!(env!("CARGO_MANIFEST_DIR"), "/src/registry/strings.rs"),
	concat!(env!("CARGO_MANIFEST_DIR"), "/src/registry/borrow_checker.rs"),
	concat!(env!("CARGO_MANIFEST_DIR"), "/src/registry/ownership_system.rs"),
	concat!(env!("CARGO_MANIFEST_DIR"), "/src/registry/sized_trait.rs"),
	concat!(env!("CARGO_MANIFEST_DIR"), "/src/registry/lifetimes.rs"),
];
